server:
  port: 9000
  error:
    include-stacktrace: never

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authorization?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1111
#  redis:
#    lettuce:
#      cluster: localhost:6379
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.hibernate:
      type:
        descriptor.sql: trace